### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by fotoflo** [kimballfrank/dpd-js-sdk#1]
Hi there
 I tried using this, but

1) i found you are using ayepromise not bluebird, so i changed the package.json and installed it, 
and then i get:

2) node_modules/dpd-js-sdk/dpd.js:183
          deferred.resolve(fn(parseBody(body)));

TypeError: undefined is not a function

Any suggestions?

**Comment by fotoflo** [comment]
Hi! It seems to work now, but the updated package is't on NPM.

**Comment by kimballfrank** [comment]
This has been resolved in the package.json file. And the Readme has also been updated.
